# Generated by Django 5.0.6 on 2024-07-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_student_academic_record_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.classes'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.student'),
        ),
    ]
