# Generated by Django 5.0.6 on 2024-07-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_academicrecord_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.classes'),
        ),
    ]
