# Generated by Django 5.0.6 on 2024-07-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_classes_teacher_teacher_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='section',
        ),
    ]
