# Generated by Django 5.0.6 on 2024-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_classes_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avaiability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
