# Generated by Django 5.0.6 on 2024-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_teacher_avaiability_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avaiability',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
