# Generated by Django 5.0.6 on 2024-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_teacher_avaiability_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days_of_week',
            field=models.ManyToManyField(to='base.dayofweek'),
        ),
    ]
