# Generated by Django 5.0.6 on 2024-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_dayofweek_remove_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='base.classes'),
        ),
    ]
