# Generated by Django 5.0.6 on 2024-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_teacher_classes_alter_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
