# Generated by Django 5.0.6 on 2024-07-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='end_date',
            new_name='exam_date',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='subject',
            new_name='exam_subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_date',
        ),
    ]
