# Generated by Django 5.0.6 on 2024-08-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_student_class_section_student_roll_number_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10),
        ),
    ]
