# Generated by Django 5.0.6 on 2024-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_subject_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='base.subject'),
        ),
    ]
