# Generated by Django 5.0.6 on 2024-08-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_section_classsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.classsection'),
        ),
    ]
