# Generated by Django 5.0.6 on 2024-08-06 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_student_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.classsection'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='base.classsection'),
        ),
    ]
