# Generated by Django 5.0.6 on 2024-08-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_academicrecord_classes_alter_exam_exam_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.classes'),
        ),
    ]
